name: Verify Dependency Licenses
description: Checks project dependencies for license compliance using Eclipse dash-licenses.

inputs:
  java-version:
    required: false
    default: '17'
  java-distribution:
    required: false
    default: 'temurin'
  working-directory:
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Create Gradle init script for dependency locking
      run: |
        mkdir -p ${{ inputs.working-directory }}/.github/workflows/scripts
        echo 'allprojects { dependencyLocking { lockAllConfigurations() } }' > ${{ inputs.working-directory }}/.github/workflows/scripts/init.gradle.kts
      shell: bash

    - name: Generate gradle.lockfile
      run: |
        echo "Generating dependency lockfile..."
        ${{ inputs.working-directory }}/gradlew --project-dir ${{ inputs.working-directory }} dependencies --write-locks --init-script ${{ inputs.working-directory }}/.github/workflows/scripts/init.gradle.kts
      shell: bash

    - name: Download Eclipse dash-licenses tool
      run: wget -O ${{ inputs.working-directory }}/dash-licenses-tool.jar 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST'
      shell: bash

    - name: Run Eclipse dash-licenses check
      run: |
        echo "Running license check with Eclipse dash-licenses..."
        cat ${{ inputs.working-directory }}/gradle.lockfile | grep -Pv '^#' | grep -Pv '^empty' | grep -Poh '^[^=]+' | java -jar ${{ inputs.working-directory }}/dash-licenses-tool.jar -summary ${{ inputs.working-directory }}/dash-summary.txt -
      shell: bash

    - name: Archive dash artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Dash Report - Run ${{ github.run_number }}
        path: ${{ inputs.working-directory }}/dash-summary.txt

    - name: Clean up init script and tool
      if: always()
      run: |
        rm -rf ${{ inputs.working-directory }}/.github/workflows/scripts
        rm -f ${{ inputs.working-directory }}/dash-licenses-tool.jar
      shell: bash